language: cpp
sudo: required
dist: trusty
services:
  - docker

env:
  global:
    - secure: "mDL8liuT/BrF83h7kTEBTyZEw/oqnT+BrN2n/Cg1pO5YsFTUU50JH1OG6mCylUW0zK6wvpvEnJ6yb/cAzW9oVk05HbKLbsU98v70oYvDtcjc7NbOTkGVcSkFELTEqqjeNxxTYe9BB1u0mgShspQStD5iiqEr3d0FqwcxtQ2vqfG55u7nH6wUrYdt850P7AXgtESD4G81y/W+SwGTljqiCtPYUapyEgyQoWbTED5X2KDWLsMvBz4wuRFAcA8ivuBm6cvZK9dw0V/bazHWNdyo2NmTPtrP3uyQPCSCbbyUvca1gcs2ZKWgieILRK9d6RzxMf0TgMrAHvdcKyV5E3jtcTzzJilx/Lx9Cei0HMAyC5gb2dlhmqg4tjNwpacGeJYVz0Kb+WB7fW5Qmhe3N32CkydMd7mWr4d8+f6kecInFF848MU40YBA3UVRrkq/DzM7uCWM9M2LHIJqk+es8w65L1o+FowAzl1krUiJWASErZnofNN0WQ/ki3NNAZXGgnmxUeg3J6XLO8M22LvarRQypij4b1PH2HrwBDbiAqIj40RmhXpddnoQEj7YtkIESc99LDGxHnVpZ6gp8BICnpw+/v+MlgoMLjJiob69FWfgC7+QfZISoqsZ2YHFGKH35INYLrrGyQ1gXhlGdhgC8bX1tRkSJyPjbr9/JqeDht9ch6A="
    - secure: "t/Y/D24dmSHzRlCqmrZDexRkqbsInPsZDOurDbPpJsPMXon9AEsoqsweijtVPO/cDtoRusW3rwhjI+eVsct3RF8ncuIavSYHqFl/QLj3HN+9H11R8lMtkYamzQcv60nYpMEyosAUufrcPyDwFbXt7lmSHPYWk6UWkmoos1kRdLGC25LqFxHNc6dGwPbfaEVQBv5wPZZzWRLH4jNA9uLhz2arZY8ZG7/9aB1DsxMpEnTS0zHyTkXq7yE9hop4KQKGXq9WVNHoKS6MOnMnZuMYL+RMdD0tH8V8tkqttRkQOQFRcz6MaKpCUb2+Buu+MJmV6QAd1N1vVVAsqoAcMuapTnZ4YRhhflV/cfzUanQDlnmdR4OUBPxeqXD3RxWz/huKAB4zX2oO+W/Rdv1VJf+5N80CpvmLgNQFIFZVOiqTGs2HoLV0pjGalav0gVR2cDqBNcgLmGzRW1GhWU0VYyCYAFqdTC0hml8G+53wUMtA9OEO4qb1wWfWIQxYDwCZR2nA9kwWUddNRKC+N+m3x935ERyFVIUXoIa+xLCtZpMloOpLwVuW5hHLlesHQXenwF2jiypoh3hJTkgQOVoNl65md7WcgCjdqekdratcoOBnL2r7oYW8yjLkaiJs/K8hFwx2OG/82HVqcNqkZ4Iyz/0EwS2FMKb3+TIOkS9Z4jqfWEg="

notifications:
  irc:
    channels:
      - "irc.quakenet.org#jk2mv"
    template:
      - "%{repository} (%{commit}): %{commit_subject}"
      - "%{message} Details: %{build_url}"

matrix:
  include:
    - os: linux
      env: HOST=linux-x86_64-gcc
    - os: osx
      env: HOST=macosx-x86_64-clang

before_install: |
  git fetch --unshallow
  
  if [[ "$HOST" == linux-x86_64-gcc ]]; then
      docker pull ubuntu:16.04
      docker run --name bc -v $TRAVIS_BUILD_DIR:/jk2mv -td ubuntu:16.04 /bin/bash
  fi

install: |
  if [[ "$HOST" == linux-x86_64-gcc ]]; then
      docker exec bc apt update
      docker exec bc apt -y install git cmake zip rpm debhelper devscripts build-essential libsdl2-dev libgl1-mesa-dev libopenal-dev
  else
      cd ~
      curl -O https://www.libsdl.org/release/SDL2-2.0.7.tar.gz
      tar xzf SDL2-2.0.7.tar.gz
      cd SDL2-2.0.7/Xcode/SDL
      sed -i -e 's/@rpath//g' SDL.xcodeproj/project.pbxproj
      xcodebuild -configuration Release
      mkdir -p ~/Library/Frameworks/
      ln -s `pwd`/build/Release/SDL2.framework ~/Library/Frameworks/
  fi

script: |
  mkdir $TRAVIS_BUILD_DIR/build/travis
  cd $TRAVIS_BUILD_DIR/build/travis
  if [[ "$HOST" == linux-x86_64-gcc ]]; then
      docker exec bc sh -c "cd /jk2mv/build/travis && cmake -DUseInternalPNG=ON -DUseInternalJPEG=ON -DUseInternalZLIB=ON -DUseInternalMiniZip=ON -DBuildPortableVersion=OFF -DBuildPackDEB=ON -DBuildPackRPM=ON ../.."
      docker exec bc sh -c "cd /jk2mv/build/travis && make"
      docker exec bc sh -c "cd /jk2mv/build/travis && make package"
  else
      cmake -G "Unix Makefiles" -DUseInternalPNG=ON -DUseInternalJPEG=ON -DUseInternalZLIB=ON -DUseInternalMiniZip=ON -DBuildPortableVersion=OFF ../..
      make
      make package
  fi

after_script: |
  if [[ "$HOST" == linux-x86_64-gcc ]]; then docker stop bc; fi

before_deploy: |
  cd $TRAVIS_BUILD_DIR
  sed -i -e "s/@MV_VERSION@/$(git describe --tags)/g" tools/bintray.json
  sed -i -e "s/@MV_DATE@/$(date -u +"%Y-%m-%d")/g" tools/bintray.json

deploy:
  skip_cleanup: true
  - provider: bintray
    file: "tools/bintray.json"
    user: "ouned"
    key: $BINTRAY_APIKEY
    on:
      tags: false
  - provider: releases
    file_glob: true
    file: build/travis/*.{deb,rpm,dmg}
    api_key: $GITHUB_APIKEY
    on:
      tags: true
